apiVersion: v1
kind: Service
metadata:
  name: demo-devops
spec:
   type: NodePort
   selector:
     app: selector-demo-devops
   ports:
     - protocol: TCP      # "targetPort"는 애플리케이션(pod)을 노출하는 포트이다.
       port: 80           # Service IP Port
       nodePort: 8080     # Node Port 번호
       targetPort: 8080   # Pod에 연결할 Port