#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: example-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: hello-world.info
#      http:
#        paths:
#          - path: /testWeb
#            pathType: Prefix
#            backend:
#              service:
#                name: web
#                port:
#                  number: 8080
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service-demo-devops
                port:
                  number: 8080